stages:
  clean_data:
    cmd: python src/data/clean_data.py data/raw/Spb_flats_prices.csv data/interim/cleaned_data.csv
    deps:
      - data/raw/Spb_flats_prices.csv
      - src/data/clean_data.py
    outs:
      - data/interim/cleaned_data.csv


  add_features:
    cmd: python src/features/add_features.py data/interim/cleaned_data.csv data/interim/added_features.csv
    deps:
      - data/interim/cleaned_data.csv
      - src/features/add_features.py
    outs:
      - data/interim/added_features.csv